name: Web - Build, Push, Deploy
on:
  push:
    paths:
      - '.github/workflows/web.yml'
      - 'apps/web/**'

jobs:
  build:
    name: Build, Push, Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build -t m3o/cloud-next .
        working-directory: ./apps/web
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Tag & Push Live
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag m3o/cloud-next registry.digitalocean.com/m3o/cloud-next:live
          docker push registry.digitalocean.com/m3o/cloud-next:live
          doctl apps create-deployment ${{ secrets.DIGITALOCEAN_LIVE_ID }}

      - name: Tag & Push Preview
        if: github.ref != 'refs/heads/main'
        run: |
          docker tag m3o/cloud-next registry.digitalocean.com/m3o/cloud-next:preview
          docker push registry.digitalocean.com/m3o/cloud-next:preview
          doctl apps create-deployment ${{ secrets.DIGITALOCEAN_PREVIEW_ID }}
